# Site
name: "Զնին.հայ"
title: "Զնին.հայ"
description: "առաջին հայալեզու քննախօսական կայքը"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
disqus: 'znin-hay'
include: ["_pages"]
permalink: /:title/
remote_theme: tigransimonyan/znin

# Authors
authors:
  tigran:
    name: Տիգրան
    display_name: Տիգրան
    avatar: 'assets/images/tigran.jpg'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    twitter: https://twitter.com/_tigransimonyan
    description: ''
  zythepsary:
    name: Սեաւ
    display_name: Սեաւ    
    avatar: 'assets/images/zythepsary.jpg'
    gravatar: b1cc14991db7a456fcd761780bbc8f81
    description: ''
  mutabor:
    name: Մութաբոր
    display_name: Մութաբոր
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    description: ''


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
